### ISSUE TITLE
 Invalid Password

### ISSUE THREAD

**Issue by Ramlakshmi135** [A-Suprasanna/MEDPEX#1]
Error message  should not be shown.

**Comment by A-Suprasanna** [comment]
Fixed that issue

**Comment by Ramlakshmi135** [comment]
![Screenshot 2024-12-10 195141](https://github.com/user-attachments/assets/51c06b2a-13fd-4db2-9dc2-c2777033bd76)

**Comment by Ramlakshmi135** [comment]
![image](https://github.com/user-attachments/assets/8f7e4fff-1668-440e-af15-62a53fac6e35)
I have retested and found the bug to be fixed. hence close the bug
