### ISSUE TITLE
BUGID018  Password Special Characters

### ISSUE THREAD

**Issue by Ramlakshmi135** [A-Suprasanna/MEDPEX#11]
I said to them use special characters but they did'nt make it  want to come special characters also.

**Comment by A-Suprasanna** [comment]
https://github.com/A-Suprasanna/MEDPEX/commit/e1ddae30481ca1ddc7e6095dac750443963b

fixed

**Comment by Ramlakshmi135** [comment]
![Uploading image.png…]()
I have retested and found the bug to be fixed. hence close the bug

**Comment by Ramlakshmi135** [comment]
![image](https://github.com/user-attachments/assets/bf76f533-89df-459b-bd25-b45ed7d1942f)
I have retested and found the bug to be fixed. hence close the bug
