### ISSUE TITLE
BUGID022  Username Too Long

### ISSUE THREAD

**Issue by Ramlakshmi135** [A-Suprasanna/MEDPEX#12]
username exceeding maximum length
should shown

**Comment by A-Suprasanna** [comment]
https://github.com/A-Suprasanna/MEDPEX/commit/e1ddae30481ca1ddc7e6095dac750443963b

fixed

**Comment by Ramlakshmi135** [comment]
![image](https://github.com/user-attachments/assets/17bc1dc7-85d1-4313-8668-eb89a77ea297)
I have retested and found the bug to be fixed. hence close the bug
