### ISSUE TITLE
BUGID023 Username Too Short

### ISSUE THREAD

**Issue by Ramlakshmi135** [A-Suprasanna/MEDPEX#13]
The system allowed a successful login even with a username shorter than the minimum length 3.

**Comment by A-Suprasanna** [comment]
https://github.com/A-Suprasanna/MEDPEX/commit/e1ddae30481ca1ddc7e6095dac750443963b

fixed

**Comment by Ramlakshmi135** [comment]
![image](https://github.com/user-attachments/assets/56fe5490-13bd-42c7-9d22-0f75cb413c69)
I have retested and found the bug to be fixed. hence close the bug
