### ISSUE TITLE
BUGID026 Password validation

### ISSUE THREAD

**Issue by Ramlakshmi135** [A-Suprasanna/MEDPEX#14]
Negative and decimal numbers are should  not be  allowed

**Comment by A-Suprasanna** [comment]
https://github.com/A-Suprasanna/MEDPEX/commit/e1ddae30481ca1ddc7e6095dac750443963b

fixed

**Comment by Ramlakshmi135** [comment]
![image](https://github.com/user-attachments/assets/6822f108-6c72-4096-bb47-3176e6770442)
I have retested and found the bug to be fixed. hence close the bug
