### ISSUE TITLE
BUGID031 Verify Header Section

### ISSUE THREAD

**Issue by Ramlakshmi135** [A-Suprasanna/MEDPEX#15]
The header section is displayed with the correct logo and navigation menu

**Comment by A-Suprasanna** [comment]
https://github.com/A-Suprasanna/MEDPEX/commit/e1ddae30481ca1ddc7e6095dac750443963b

fixed

**Comment by Ramlakshmi135** [comment]
![image](https://github.com/user-attachments/assets/9e7aab43-2cf1-4ddd-bb18-53051448698b)
I have retested and found the bug to be fixed. hence close the bug
