### ISSUE TITLE
BUGID038 Hero Section Verification

### ISSUE THREAD

**Issue by Ramlakshmi135** [A-Suprasanna/MEDPEX#17]
The Hero Section is displayed correctly and contains all required elements. but background image should not be shown

**Comment by A-Suprasanna** [comment]
https://github.com/A-Suprasanna/MEDPEX/commit/e1ddae30481ca1ddc7e6095dac750443963b

fixed

**Comment by Ramlakshmi135** [comment]
![image](https://github.com/user-attachments/assets/ea56e2d5-3a65-42e7-a337-fa53209c40a5)

I have retested and found the bug to be fixed. hence close the bug
