### ISSUE TITLE
Verify Navigation Bar Functionality

### ISSUE THREAD

**Issue by Ramlakshmi135** [A-Suprasanna/MEDPEX#2]
The Navigation Bar is displayed correctly, all menu items are clickable, but function is not working

**Comment by A-Suprasanna** [comment]
fixed that

**Comment by Ramlakshmi135** [comment]
![image](https://github.com/user-attachments/assets/5bceeb53-4fd5-4e4c-b7b3-4fe61c7886cd)
I have retested and found the bug to be fixed. hence close the bug
