### ISSUE TITLE
BUGID004 Email validation 

### ISSUE THREAD

**Issue by Ramlakshmi135** [A-Suprasanna/MEDPEX#5]
Error message: "Invalid email address." The form is not sent.

**Comment by Ramlakshmi135** [comment]
![image](https://github.com/user-attachments/assets/4831bd3f-8e89-41dd-bcff-8367793d1829)


I have retested and found the bug to be fixed. hence close the bug

**Comment by A-Suprasanna** [comment]
https://github.com/A-Suprasanna/MEDPEX/commit/3ad4ac30a683505f0e21cf5b431adca873ff8871

fixed
