### ISSUE TITLE
BUGID001  Valid Username

### ISSUE THREAD

**Issue by Ramlakshmi135** [A-Suprasanna/MEDPEX#6]
The username must be valid

**Comment by A-Suprasanna** [comment]
https://github.com/A-Suprasanna/MEDPEX/commit/e1ddae30481ca1ddc7e6095dac750443963b

fixed

**Comment by Ramlakshmi135** [comment]
![image](https://github.com/user-attachments/assets/631a61bd-b8f3-476d-8b2c-29711b0acec3)
I have retested and found the bug to be fixed. hence close the bug
