### ISSUE TITLE
BUGID007 Password Minimum Length validation

### ISSUE THREAD

**Issue by Ramlakshmi135** [A-Suprasanna/MEDPEX#8]
The password error message should be shown the exact minimum and maximum length. but function is not working

**Comment by A-Suprasanna** [comment]
https://github.com/A-Suprasanna/MEDPEX/commit/e1ddae30481ca1ddc7e6095dac750443963b

fixed

**Comment by Ramlakshmi135** [comment]
![image](https://github.com/user-attachments/assets/d0c28ce7-47c9-490b-bff7-c6baa7127b81)
I have retested and found the bug to be fixed. hence close the bug
