### ISSUE TITLE
BUGID015 Confirm password validation

### ISSUE THREAD

**Issue by Ramlakshmi135** [A-Suprasanna/MEDPEX#9]
The password error message should be shown I said to them use special characters but they did'nt make it  want to come special characters also .

**Comment by A-Suprasanna** [comment]
https://github.com/A-Suprasanna/MEDPEX/commit/e1ddae30481ca1ddc7e6095dac750443963b

fixed

**Comment by Ramlakshmi135** [comment]
![image](https://github.com/user-attachments/assets/3c6514a4-44de-4b6e-8d4a-16138f3eb94d)
I have retested and found the bug to be fixed. hence close the bug
